version: '3.1'

services:
  db:
    image: postgres:9-alpine
    environment:
      POSTGRES_PASSWORD: azucar
      POSTGRES_USER: ruben
      POSTGRES_DATABASE: ruben_development
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"