version: 2
jobs:
  build:
    # Primary container image where all commands run
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          POSTGRES_USER: ruben
          POSTGRES_PASS: azucar

      # Service container image available at `host: localhost`

      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: ruben
          POSTGRES_PASSWORD: azucar
          POSTGRES_DB: ruben_test

    steps:
      - checkout

      # Update Bundler
      - run:
          name: Update Bundler
          command: gem install bundler:1.17.2
      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle install

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate

      - run:
          name: RSpec
          command: bundle exec rspec

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
